### ISSUE TITLE
Pivot wider fails when the class of variable is a vector longer than one.

### ISSUE THREAD

**Issue by jwilliman** [tidyverse/tidyr#780] opened 2019-10-17 21:54 UTC
When running `pivot_wider` over data where one of the character variables is labelled using the `Hmisc::label` function, I get the warning message `Error: Only bare vectors have shapes.` 

The `Hmisc::label` function not only adds a `label` attribute to the variable, but it changes the variable class to `c("labelled", "character")`.

I found that I could reproduce this error by adding to the `class` of any variable prior to using `pivot_wider`. Interestingly, this doesn't occur for factors - so I'm guessing factor variables are treated differently?

I'm not sure if editing the class of a variable is peculiar to `Hmisc` (and should be corrected there), or whether it should be considered acceptable in general and thus catered for?

```r

## This works
data("fish_encounters")
fish_encounters$fish <- as.character(fish_encounters$fish)
fish_encounters %>% pivot_wider(names_from = station, values_from = seen)

## So does this
data("fish_encounters")
class(fish_encounters$fish) <- c("factor", "extra")
fish_encounters %>% pivot_wider(names_from = station, values_from = seen)

## But these all fail
data("fish_encounters")
fish_encounters$fish <- as.character(fish_encounters$fish)
class(fish_encounters$fish) <- c("character", "extra")
fish_encounters %>% pivot_wider(names_from = station, values_from = seen)

data("fish_encounters")
fish_encounters$station<- as.character(fish_encounters$station)
class(fish_encounters$station) <- c("character", "extra")
fish_encounters %>% pivot_wider(names_from = station, values_from = seen)

data("fish_encounters")
class(fish_encounters$seen) <- c("integer", "extra")
fish_encounters %>% pivot_wider(names_from = station, values_from = seen)

```

**Comment by hadley** [comment] 2019-10-18 11:41
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by jeffreypullin** [comment] 2019-10-19 11:24
Minimal reprex: 

``` r
x <- 1:10
Hmisc::label(x) <- "x's label"
vctrs:::shape(x)
#> Only bare vectors have shapes.
```
<sup>Created on 2019-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So this is a duplicate of #773 and hence r-lib/vctrs#614.

**Comment by hadley** [comment] 2019-10-19 13:06
Thanks for the investigation @jeffreypullin!

**Closed by hadley** 2019-10-19 13:06 UTC
