### ISSUE TITLE
unnest no longer works for AsIs columns?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/tidyr#1298] opened 2022-01-09 05:22 UTC
Hi, I'm trying to update from `tidyr` 1.1.3 to 1.1.4 and noticed it broke some tests. It looks like this is an MRE:

```
DF = data.frame(a = 1:2, b = I(list(3:4, 5:6)))
tidyr::unnest(DF, "b")
```

output in tidyr:1.1.3
```
# A tibble: 4 x 2
      a     b
  <int> <int>
1     1     3
2     1     4
3     2     5
4     2     6
```

vs in tidyr:1.1.4
```
# A tibble: 2 x 2
      a b        
  <int> <I<list>>
1     1 <int [2]>
2     2 <int [2]>
```

We can solve this by doing `class(DF$b) = NULL`, but I don't see this mentioned in the NEWS, so I'm wondering if it's an unintended regression / bug.

**Comment by MichaelChirico** [comment] 2022-01-09 05:27
It looks like the issue is the move to rely on `vctrs::vec_is_list()`:

ba73124b8651877dfd784110f14d0ebf280de8b6

https://github.com/r-lib/vctrs/blob/f9afbff431da9d0b711db2b54be4c3ee925c6e5b/src/type-info.c#L109-L123

`vec_is_list()` excludes classed lists. Should this just be `is.list()` instead?

**Comment by DavisVaughan** [comment] 2022-01-10 13:54
Duplicate of #1162, really tracking in [#1463](https://github.com/r-lib/vctrs/issues/1463) (so I'm going to close this since we know about it, but thanks!).

The move to `vec_is_list()` is intentional, as it returns `FALSE` for things like data frames and `"lm"` objects, which we want here. But the AsIs class is an extreme special case where we sort of want to ignore that class and treat the object as if that class wasn't there at all - which requires a fix in vctrs.

**Closed by DavisVaughan** 2022-01-10 13:54 UTC
