### ISSUE TITLE
tidyr not gathering all columns

### ISSUE THREAD

**Issue by jebyrnes** [tidyverse/tidyr#241] opened 2016-09-26 13:46 UTC
I'm having the oddest error - gather seems to be failing to behave properly and is not gathering some (but not all) columns of my data frame.  I first saw this bug using the version on CRAN - 0.60, and then replicated it using the version 0.6.0.9000 on github.

A test data frame can be found at https://github.com/jebyrnes/temp_kelp_change/blob/wsn2016/R/testFrame.Rdata

The column names are Year, and then text that provides some geospatial info (this was read in using readxl)

```

> testFrame

# A tibble: 5 x 128
   Year X_-177_52 X_-172.5_52 X_-168_53 X_-136.5_58 X_-132_53 X_-130.5_52 X_-127.5_50
  <dbl>     <dbl>       <dbl>     <dbl>       <dbl>     <dbl>       <dbl>       <dbl>
1  1948  18.92202    31.99949  26.22659    24.77964  19.51071    25.45549    31.95351
2  1949  21.84839    38.56399  35.52847    24.52558  19.66623    27.10531    30.59906
3  1950  18.62068    31.83611  26.27982    16.50037  16.09070    25.52311    28.28087
4  1951  27.07516    42.79150  37.57914    23.51683  19.18399    25.97696    31.89758
5  1952  32.49216    53.16526  45.59156    32.97890  24.09068    33.77699    39.93963
# ... with 120 more variables: X_-124.5_42 <dbl>, X_-124.5_43 <dbl>, X_-124.5_45 <dbl>,

```

etc.

But - when I use gather

```

library(tidyr)
gather(testFrame, coords, value, -Year)

```

32 of the columns aren't gathered.

```

# A tibble: 635 × 33
    Year `X_-10.5_54` `X_-9_55` X_4.5_60 X_4.5_61  X_12_66 `X_19.5_-35` `X_114_-30`
   <dbl>        <dbl>     <dbl>    <dbl>    <dbl>    <dbl>        <dbl>       <dbl>
1   1948     60.82195  47.23355 28.23101 30.58798 35.59740     55.46100    55.45530
2   1949     67.83090  58.29622 32.84545 35.60135 39.23950     35.20486    48.48567
3   1950     70.12429  55.86813 25.87782 27.29134 25.63699     44.73562    51.95860
4   1951     65.92518  53.26399 25.18818 26.39733 23.60435     41.27860    51.51082
5   1952     55.98658  46.88677 23.52012 25.40672 20.98253     44.95484    57.07527
6   1948     60.82195  47.23355 28.23101 30.58798 35.59740     55.46100    55.45530
7   1949     67.83090  58.29622 32.84545 35.60135 39.23950     35.20486    48.48567
8   1950     70.12429  55.86813 25.87782 27.29134 25.63699     44.73562    51.95860
9   1951     65.92518  53.26399 25.18818 26.39733 23.60435     41.27860    51.51082
10  1952     55.98658  46.88677 23.52012 25.40672 20.98253     44.95484    57.07527
# ... with 625 more rows, and 25 more variables: `X_115.5_-32` <dbl>, `X_115.5_-31` <dbl>,
#   `X_138_-36` <dbl>, X_139.5_42 <dbl>, `X_144_-41` <dbl>, `X_144_-39` <dbl>,
#   `X_145.5_-43` <dbl>, `X_145.5_-39` <dbl>, `X_147_-39` <dbl>, `X_148.5_-43` <dbl>,
#   `X_148.5_-42` <dbl>, `X_148.5_-41` <dbl>, `X_148.5_-40` <dbl>, `X_150_-38` <dbl>,
#   `X_151.5_-35` <dbl>, `X_151.5_-34` <dbl>, X_172.5_53 <dbl>, X_174_53 <dbl>,
#   `X_175.5_-37` <dbl>, `X_175.5_-36` <dbl>, X_177_52 <dbl>, X_178.5_51 <dbl>, X_180_51 <dbl>,
#   coords <chr>, value <dbl>
```

I suspect there's something going on where tidyr interacts poorly with this style of column name, but, for the life of me I cannot understand what it is, as many similar looking columns _are_ gathered properly.

**Comment by jebyrnes** [comment] 2016-09-26 13:50
Note: I first saw this bug using the version on CRAN - 0.60, and then replicated it using the version  0.6.0.9000 on github.

**Comment by hadley** [comment] 2017-06-23 20:00
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by huftis** [comment] 2017-08-04 13:45
`gather()` no longer gives the same output. It now just outputs an error message:

    Error: Data source must be a dictionary

The reason is that the example data frame (tibble) contains duplicated column names. If you remove them, everything works fine.

I tried creating a simple reprex based on the example data set, but it’s no longer possible to create tibbles with duplicate column names. For example, `tibble(x1=1:5, x1=6:10, x2=11:15)` just outputs the (quite confusing) `Data source must be a dictionary` error message. (If you remove the `x2` variable, the error message is changed to `Column x1 must have a unique name`.)

**Comment by hadley** [comment] 2017-11-15 01:26
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-15 01:26 UTC
Labels: reprex
