### ISSUE TITLE
Performance issue when nesting dates

### ISSUE THREAD

**Issue by kendonB** [tidyverse/tidyr#369] opened 2017-10-23 00:42 UTC
I find that nesting data that contains dates is quite slow and I get a major performance improvement by "manually" nesting the first of two groups using a loop.

``` r
library(tidyverse)
library(lubridate)
tmp <- crossing(a = 1:30,
                b = 1:30,
                value = as_date(1:1000)) 

# This first one is an indirect way
# to nest the data.frame
system.time({
  tmp2 <- map(unique(tmp$a), function(.a){
    tmp %>% 
      filter(a == .a) %>% 
      group_by(a, b) %>% 
      nest()
  }) %>% 
    bind_rows()
})
#>    user  system elapsed 
#>    1.69    0.04    1.73
                                        
# This is much slower
system.time({
  tmp3 <- 
    tmp %>% 
    group_by(a, b) %>% 
    nest()
})
#>    user  system elapsed 
#>    3.70    1.73    5.58
                                        
identical(tmp2, tmp3)                   
#> [1] TRUE
```

I find that the crunching time increases linearly for both the usual and "manual" nesting methods; as in, the gap continues to widen.

**Comment by hadley** [comment] 2017-11-16 01:26
``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-15

library(tidyr)

tmp <- crossing(
  a = 1:25,
  b = 1:25,
  v1 = lubridate::as_date(1:1000)
) %>% 
  dplyr::mutate(v2 = as.numeric(v1))

# slow
system.time(tmp %>% dplyr::group_by(a, b) %>% nest(v1))
#>    user  system elapsed 
#>   1.468   0.518   2.000
# fast
system.time(tmp %>% dplyr::group_by(a, b) %>% nest(v2))
#>    user  system elapsed 
#>   0.209   0.008   0.218
```

**Comment by hadley** [comment] 2017-11-16 01:30
A little profiling reveals that the culprit is `split.data.frame()`:

``` r
  system.time(split(tmp["v1"], list(tmp$a, tmp$b)))
#>    user  system elapsed 
#>   1.529   0.525   2.064
  system.time(split(tmp["v2"], list(tmp$a, tmp$b)))
#>    user  system elapsed 
#>   0.147   0.013   0.161
```

So improving performance here probably means implementing our own split function.

**Comment by hadley** [comment] 2017-11-20 18:50
But the root cause of that slowness is `[.Date` so I think fixing this is out of scope for tidyr. I've sent an email to R-devel.

**Closed by hadley** 2017-11-20 18:50 UTC
Labels: bug, trees
