### ISSUE TITLE
spread kill rsession on 5G data with over 1000 different keys

### ISSUE THREAD

**Issue by jerryfuyu0104** [tidyverse/tidyr#381] opened 2017-11-17 07:56 UTC
i have a long data to wide data with the func spread,
the data is much big which is over 5G, and the key has 1000 different values,
if i run the code, the rsession will be killed.
  frm_scores <- frm_scores %>%
    spread(key = SCORE_NAME, value = ALPHA)

**Comment by hadley** [comment] 2017-11-17 13:44
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-11-22 12:48
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-22 12:48 UTC
Labels: reprex
