### ISSUE TITLE
order of pivoted columns with pivot_wider

### ISSUE THREAD

**Issue by eantworth** [tidyverse/tidyr#850] opened 2020-01-06 20:12 UTC
I'm trying to force the order of pivoted columns by using factor levels. This works with spread, but appears not to work with pivot_wider.  See example attached.
[pivot_wider_example_2020-01-06.zip](https://github.com/tidyverse/tidyr/files/4027636/pivot_wider_example_2020-01-06.zip)

**Comment by hadley** [comment] 2020-01-06 21:01
Duplicate of #839.

In the future, can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Closed by hadley** 2020-01-06 21:01 UTC
