### ISSUE TITLE
Document c(col1, col2) tidyselect specification for pivot_longer()

### ISSUE THREAD

**Issue by nacnudus** [tidyverse/tidyr#862] opened 2020-01-28 11:15 UTC
I couldn't find out from any documentation how to name multiple columns in the `cols` argument of `pivot_longer()`.  This would be equivalent to the `...` argument of `gather()`.

Eventually I guessed that `c(col_name_1, col_name_2)` works.

The four statements below all do the same thing, and could be given in the documentation for `pivot_longer()` and `vignette("pivot")`.

```r
# Including more than one column in `cols` by name
smiths %>%
  gather("key", "value", age, weight, height)

smiths %>%
  pivot_longer(c(age, weight, height), names_to = "metric")

# Excluding more than one column in `cols` by name
smiths %>%
  gather("key", "value", -subject, -time)

smiths %>%
  pivot_longer(c(-subject, -time), names_to = "metric")
```

**Comment by hadley** [comment] 2020-04-01 17:11
Duplicate of #872

**Closed by hadley** 2020-04-01 17:11 UTC
