### ISSUE TITLE
unnest inconsistent when (a) naming new column and (b) list-col has length-one entry

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/tidyr#330] opened 2017-07-21 01:06 UTC
```R
 > df1 <- tibble(a = "foo", b = list(c("bar", "baz")))
 > df2 <- tibble(a = "foo", b = list(c("bar")))
 > df1
 # A tibble: 1 x 2
       a         b
   <chr>    <list>
 1   foo <chr [2]>
!> df2
 # A tibble: 1 x 2
       a         b
   <chr>    <list>
 1   foo <chr [1]>
```
Now, when `unnest`ing `b` _without_ specifying the new column's name, the output is consistent between `df1` and `df2`:
```R
 > unnest(df1, b)
 # A tibble: 2 x 2
       a     b
   <chr> <chr>
 1   foo   bar
 2   foo   baz
 > unnest(df2, b)
 # A tibble: 1 x 2
       a     b
   <chr> <chr>
 1   foo   bar
```
But when specifying that the new column take a new name, the nested column remains around _only_ for the case where the list-col entry has length one:
```R
 > unnest(df1, new_b = b)
 # A tibble: 2 x 2
       a new_b
   <chr> <chr>
 1   foo   bar
 2   foo   baz
 > unnest(df2, new_b = b)
 # A tibble: 1 x 3
       a         b new_b
   <chr>    <list> <chr>
 1   foo <chr [1]>   bar
```
Note that the last `unnest` call retains the original column `b`.
Smells like a (minor) edge-case bug.

<details>
<summary>tidyverse version(s):</summary>
<pre>
 + ggplot2 2.2.1             Date: 2017-07-20
 + tibble  1.3.0.9010           R: 3.3.3
 + tidyr   0.6.3               OS: Amazon Linux AMI 2017.03
 + readr   1.1.1.9000         GUI: X11
 + purrr   0.2.2.9000      Locale: en_US.UTF-8
 + dplyr   0.5.0.9000          TZ: America/Denver
 + stringr 1.2.0
 + forcats 0.2.0
</pre>
</details>

**Comment by mmuurr** [comment] 2017-07-21 01:12
I should add that using `.drop = TRUE` removes `b` from the last example, so if one is explicit there's no bug... it's only the implicit `.drop = NA` case that's affected.

**Comment by hadley** [comment] 2017-11-15 01:12
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment] 2017-11-15 01:32
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-15 01:32 UTC
Labels: reprex
