### ISSUE TITLE
tidyr::crossing, Warning: is.na(name) : is.na() applied to non-(list or vector) of type 'NULL'

### ISSUE THREAD

**Issue by srnnkls** [tidyverse/tidyr#762] opened 2019-09-25 09:49 UTC
`tidyr::crossing` in 1.0 returns a warning about `is.na()` applied to `NULL` vectors, whereas `tidyr::expand_grid` does not.

``` r
library(tidyverse)
tibble(a = 1:5, b = letters[1:5]) %>% crossing(c = c(1,2))
#> Warning in is.na(name): is.na() applied to non-(list or vector) of type
#> 'NULL'
#> # A tibble: 10 x 3
#>        a b         c
#>    <int> <chr> <dbl>
#>  1     1 a         1
#>  2     1 a         2
#>  3     2 b         1
#>  4     2 b         2
#>  5     3 c         1
#>  6     3 c         2
#>  7     4 d         1
#>  8     4 d         2
#>  9     5 e         1
#> 10     5 e         2
tibble(a = 1:5, b = letters[1:5]) %>% expand_grid(c = c(1,2))
#> # A tibble: 10 x 3
#>        a b         c
#>    <int> <chr> <dbl>
#>  1     1 a         1
#>  2     1 a         2
#>  3     2 b         1
#>  4     2 b         2
#>  5     3 c         1
#>  6     3 c         2
#>  7     4 d         1
#>  8     4 d         2
#>  9     5 e         1
#> 10     5 e         2
```
<sup>Created on 2019-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment] 2019-09-30 22:51
I can't reproduce this, even with CRAN tidyr (v1.0.0) so I suspect it's already fixed in the dev version of a dependency.

**Closed** 2019-11-13 21:51 UTC
