### ISSUE TITLE
Inconsistency between separate() and stringr::str_split_fixed()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/tidyr#252] opened 2016-10-08 03:54 UTC
It feels like `tidyr::separate()` and `stringr::str_split_fixed()` should be consistent re: too few pieces (`NA` vs empty string). The empty string makes more sense in terms of round trips, e.g. `separate()` + `unite()`.

``` r
library(tidyr)
library(stringr)
library(tibble)

berries <- fruit[31:33]
tibble(berries) %>% 
  tidyr::separate(berries, into = c("pre", "post"), sep = " ")
#> Warning: Too few values at 2 locations: 1, 3
#> # A tibble: 3 × 2
#>          pre  post
#> *      <chr> <chr>
#> 1        fig  <NA>
#> 2       goji berry
#> 3 gooseberry  <NA>
berries %>% 
  str_split_fixed(pattern = " ", n = 2) %>% 
  as_tibble()
#> # A tibble: 3 × 2
#>           V1    V2
#>        <chr> <chr>
#> 1        fig      
#> 2       goji berry
#> 3 gooseberry
```

**Comment by hadley** [comment] 2017-11-16 20:51
I think the problem is actually `str_split_fixed()` - stringr has been slowly moving to always use `NA` for missing matches. Issue filed at https://github.com/tidyverse/stringr/issues/195

**Closed by hadley** 2017-11-16 20:51 UTC
Labels: feature, strings
