### ISSUE TITLE
Potential Issue: object is losing its class (e.g., when being used with an sf object)

### ISSUE THREAD

**Issue by mcarauta** [tidyverse/tidyr#1495] opened 2023-04-25 07:45 UTC
Dear All,

I tried to use this new function separate_wider_delim() with an sf object (map loaded with the sf package), and the object lost its "sf" class. Therefore, I could not use it to plot charts in ggplot2. Despite still seeying a column geometry, ggplot returned me an error message saying that there was no geometry...

Appeciate your support here.

By the way, I managed to find a work around to this problem by using the old function separate().

**Comment by hadley** [comment] 2023-11-01 19:14
Duplicate of #1498

**Closed** 2023-11-01 19:14 UTC
