### ISSUE TITLE
pivot_wider and pivot_longer need to document "tidyselect specification"

### ISSUE THREAD

**Issue by tomhopper** [tidyverse/tidyr#903] opened 2020-03-06 13:23 UTC
The help files for `pivot_longer()` and `pivot_wider()`, which replace tidyr's core functions `gather()` and `spread()`, state that the main argument, `cols`, "takes a tidyselect specification." Nowhere is this "tidyselect specification" defined within the help files for these functions, no links are provided to such documentation, and no examples are offered.

The functions are unusable without a full understanding of the "tidyselect specification." This is a serious oversight in the current tidyr package.

**Comment by hadley** [comment] 2020-03-06 17:09
Duplicate of #872

**Closed by hadley** 2020-03-06 17:09 UTC
