### ISSUE TITLE
Unnest() pgkdown page version 0.8.3 available via google

### ISSUE THREAD

**Issue by Megaira** [tidyverse/tidyr#1047] opened 2020-09-23 17:09 UTC
Hello and thanks for the great package!

When `nest` and  `unnest` where moved into one file in https://github.com/tidyverse/tidyr/commit/03bb1985f364938953eced375504096d3e222d98 the old unnest documentation remained available and can be found via google: https://tidyr.tidyverse.org/reference/unnest.html (vs. the up-to-date one: https://tidyr.tidyverse.org/reference/nest.html)

**Comment by jennybc** [comment] 2020-09-23 17:29
Looks like a duplicate of #1042

**Closed** 2020-09-23 18:00 UTC
