### ISSUE TITLE
pivot_longer throws error with haven_labelled columns

### ISSUE THREAD

**Issue by cloversleaves** [tidyverse/tidyr#831] opened 2019-12-13 02:12 UTC
---

In a similar instance as below but for a bigger dataset imported with `haven`, `haven_labelled` variables do not seem to work quite right with `pivot_longer` . But `pivot_longer` does work if  `haven` attributes are removed prior to using `pivot_longer`.  The below reprex is from the `pivot_longer` vignette but I added some haven labels. 
Thank you for the great package!!! 
```r
library(tidyverse)
library(haven)

family <- tribble(
  ~family,  ~dob_child1,  ~dob_child2, ~gender_child1, ~gender_child2,
  1L, "1998-11-26", "2000-01-29",             1L,             2L,
  2L, "1996-06-22",           NA,             2L,             NA,
  3L, "2002-07-11", "2004-04-05",             2L,             2L,
  4L, "2004-10-10", "2009-08-27",             1L,             1L,
  5L, "2000-12-05", "2005-02-28",             2L,             1L,
  )


family$dob_child1<-labelled(family$dob_child1,NULL, label = "test_label") 
family$dob_child2<-labelled(family$dob_child2,NULL, label = "test_label2") 


family %>% 
  pivot_longer(
    -family, 
    names_to = c(".value", "child"), 
    names_sep = "_", 
    values_drop_na = TRUE
  )
#> Error: No common type for `dob_child1` <haven_labelled> and `dob_child2` <haven_labelled>.
```

**Comment by hadley** [comment] 2019-12-13 13:05
Duplicate of https://github.com/tidyverse/haven/issues/477

**Closed by hadley** 2019-12-13 13:05 UTC

**Comment by DanChaltiel** [comment] 2020-04-04 12:07
Actually, if there was a way to fix this inside `tidyr`, it might improve the compatibility with other labeling packages than `haven`, such as `expss` and `Hmisc`.

For instance, this code fails:

```r
library(tidyr)
fish_encounters %>%
    expss::apply_labels(seen="Is fish seen") %>%
    pivot_wider(names_from = station, values_from = seen)
```
With the error 

> `Error : Can't cast `value` <labelled> to `x` <labelled>.`

Commenting the second line goes back to `pivot_wider` help example, with obviously no error. 

Using `Hmisc::label` will have the exact same behavior.

```r
Hmisc::label(fish_encounters$seen) = "Is fish seen"
fish_encounters %>%
    pivot_wider(names_from = station, values_from = seen)
```

BTW, I find it a good practice to always paste-collapse classes when I make error messages about them. It prevents this kind of behavior on multiclass objects, when only the first class is printed.
