### ISSUE TITLE
Nested list-column is not a list and doesn't act like one

### ISSUE THREAD

**Issue by kent37** [tidyverse/tidyr#771] opened 2019-10-03 15:59 UTC
The list-column created by `nest` is not actually a `list`, it is a `vctrs_list_of`. This changes the behavior of the column. Specifically, it used to be possible to mutate values of the list-column in place by adding new columns; that no longer works.

I encountered this when adding columns to a very wide data frame; in that case the error message was truncated and un-helpful.

``` r
library(tibble)
library(tidyr)
suppressPackageStartupMessages(library(dplyr))

df = tibble(x=rep(c('a', 'b'), each=10), y=rnorm(20), z=1:20)
df_data = df %>% nest(data=-x) %>% pull(data) %>% setNames(c('a', 'b'))
class(df_data)
#> [1] "vctrs_list_of" "vctrs_vctr"

# Doesn't work
df_data$a = df_data$a %>% mutate(w=1:10)
#> Lossy cast from <tbl_df<
#>   y: double
#>   z: integer
#>   w: integer
#> >> to <tbl_df<
#>   y: double
#>   z: integer
#> >>.
#> Dropped variables: `w`

# Works
df_data = as.list(df_data)
df_data$a = df_data$a %>% mutate(w=1:10)
```

<sup>Created on 2019-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.1 (2019-07-05)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2019-10-03                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  callr         3.3.2   2019-09-22 [1] CRAN (R 3.6.1)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.2.1   2019-09-24 [1] CRAN (R 3.6.1)
#>  digest        0.6.21  2019-09-20 [1] CRAN (R 3.6.1)
#>  dplyr       * 0.8.3   2019-07-04 [1] CRAN (R 3.6.1)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.0)
#>  knitr         1.25    2019-09-18 [1] CRAN (R 3.6.1)
#>  lifecycle     0.1.0   2019-08-01 [1] CRAN (R 3.6.1)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  pillar        1.4.2   2019-06-29 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.5   2019-08-26 [1] CRAN (R 3.6.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.1)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
#>  purrr         0.3.2   2019-03-15 [1] CRAN (R 3.6.0)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.6.1)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)
#>  rlang         0.4.0   2019-06-25 [1] CRAN (R 3.6.0)
#>  rmarkdown     1.15    2019-08-21 [1] CRAN (R 3.6.1)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.2.1   2019-07-25 [1] CRAN (R 3.6.1)
#>  tibble      * 2.1.3   2019-06-06 [1] CRAN (R 3.6.0)
#>  tidyr       * 1.0.0   2019-09-11 [1] CRAN (R 3.6.1)
#>  tidyselect    0.2.5   2018-10-11 [1] CRAN (R 3.6.0)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
#>  vctrs         0.2.0   2019-07-05 [1] CRAN (R 3.6.1)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.9     2019-08-21 [1] CRAN (R 3.6.1)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#>  zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.6.0)
#> 
#> [1] C:/Program Files/R/Library
#> [2] C:/Program Files/R/R-3.6.1/library
```

**Comment by jennybc** [comment] 2019-10-03 17:11
Addressing this is already underway / under discussion in vctrs, which is where it must happen: https://github.com/r-lib/vctrs/pull/593

**Comment by jennybc** [comment] 2019-10-03 17:11
So this is essentially a duplicate of #750

**Comment by hadley** [comment] 2019-10-03 18:15
I think this might be slightly different (although the root cause is the same)

**Comment by hadley** [comment] 2019-10-11 18:20
Here the problem is that you are suffering due to the stricter type coercion logic that we have implemented in vctrs. You can expose the problem without any tidyr or dplyr:

``` r
library(vctrs)
library(tibble)

x <- list_of(
  tibble(x = 1),
  tibble(x = 2)
)

x[[2]] <- 1
#> No common type for `value` <double> and `x` <tbl_df<x:double>>.

x[[2]] <- tibble(y = 1)
#> Lossy cast from <tbl_df<y:double>> to <tbl_df<x:double>>.
#> Dropped variables: `y`
```

<sup>Created on 2019-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

At this point in time, I'd say this behaviour is unlikely to change. We may consider changing it if many people find it annoying, but we're generally trying to be a bit stricter than base R because we think behaviour like the following is a rich source of bugs:

``` r
x <- 1:5
x[[2]] <- "x"
x
#> [1] "1" "x" "3" "4" "5"
```

For your specific case, you can either convert the column to a list, or replace values en masse by using `map()` or similar.

**Closed by hadley** 2019-10-11 18:20 UTC

**Comment by kent37** [comment] 2019-10-11 19:17
Yes, my solution was to convert the list-column to a list.

It might be worth pointing out in `?nest` that the list-column it creates is not a list, it is a homogeneous collection.
