### ISSUE TITLE
separate() causes R to crash with fatal error

### ISSUE THREAD

**Issue by jgellar** [tidyverse/tidyr#297] opened 2017-04-25 16:25 UTC
I have a dataset in wide format. There are 11 primary variables, but each one appears in the dataset in 72 columns: once for each month, for 6 years. Each of these variable names ends in ".YYYY_M", where YYYY is a 4-digit year and M is either a 1 or 2 digit month. For example, "MY_VARIABLE.2009_1" referring to January 2009. The total dimensions of the dataset, in wide format, are 266879 x 794 (11 wide variables * 72 months + 2 other identifying variables = 794 columns).

I am trying to convert the dataset to long format. My plan was to first gather all the relevant variables in a single column, then separate out the time, then spread the 11 variables back out. The following code attempts to do that.

```
vnms <- names(outs_TN_wide)
vars_tv <- grepl("20[01]\\d", vnms)

outs_TN_long <- outs_TN_wide %>%
  gather(Variable, Value, one_of(vnms[vars_tv])) %>%
  separate(Variable, c("Variable", "Time"), sep = "\\.")
```
However, every time I run the code, my R session crashes ("R encountered a fatal error./The session was terminated"). The problem is definitely the `separate` step, because I can run the `gather` by itself with no problem. In fact, gathering only takes a couple seconds.

Is the dataset simply too big? Separating seems like a pretty innocuous step in comparison to the gather, it's strange that it would cause such problems. After the gather step, the dataset is 211368168 x 4.

Any explanation/suggestions would be appreciated.

**Comment by hadley** [comment] 2017-06-23 20:51
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page.

**Comment by hadley** [comment] 2017-11-15 01:28
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-15 01:28 UTC
Labels: reprex

**Comment by bastianolea** [comment] 2020-12-03 20:17
```
data <- tibble(encuesta = c(1990, 1990, 1990, 1991, 1991, 1991, 1991, 1992, 1992, 1992, 1993, 1993, 1993, 1993, 1994, 1995, 1995, 1996, 1996, 1997, 1997,
1998, 1999, 1999, 2000, 2000, 2001, 2001, 2002, 2002, 2003, 2003, 2004, 2004, 2005, 2005, 2005, 2006, 2006, 2006, 2007, 2007,
2008, 2008, 2009, 2009, 2009, 2010, 2010, 2011, 2011, 2012, 2012, 2012, 2013, 2013, 2014, 2014, 2015, 2015, 2015, 2016, 2016,
2016, 2017, 2017, 2017, 2018, 2019, 2019),
meses = c("Mayo y Junio",
"Septiembre y Octubre",
"Diciembre",
"Marzo",
"Junio y Julio",
"Septiembre y Octubre",
"Diciembre y Enero",
"Abril",
"Agosto",
"Diciembre",
"Marzo",
"Junio y Julio",
"Octubre y Noviembre",
"Noviembre",
"Noviembre y ",
"Mayo y Junio",
"Noviembre",
"Junio y Julio",
"Noviembre y Diciembre",
"Junio y Juilio",
"Diciembre y Enero",
"Junio",
"Abril y Mayo",
"Septiembre y Octubre",
"Marzo y Abril",
"Noviembre y Diciembre",
"Junio",
"Diciembre",
"Julio",
"Diciembre",
"Junio y Julio",
"Diciembre",
"Junio y Julio",
"Diciembre",
"Junio y Julio",
"Agosto y Septiembre",
"Octubre y Noviembre",
"Junio y Julio",
"Mayo",
"Diciembre",
"Junio",
"Noviembre y Diciembre",
"Junio",
"Noviembre y Diciembre",
"Mayo y Junio",
"Agosto",
"Octubre",
"Junio y Julio",
"Noviembre y ",
"Junio y Julio",
"Noviembre y Diciembre",
"Abril",
"Julio y Agosto",
"Noviembre y Diciembre",
"Julio y Agosto",
"Septiembre y Octubre",
"Julio",
"Noviembre",
"Abril",
"Agosto",
"Noviembre",
"Marzo, Abril y Mayo",
"Julio y Agosto",
"Noviembre y Diciembre",
"Abril y Mayo",
"Julio y Agosto",
"Septiembre y Octubre",
"Octubre y Noviembre",
"Mayo",
"Diciembre"))

data %>%
  separate(col = meses, 
                  into=c("mes_inicio", "mes_fin"), 
                  sep="y") 
```
