### ISSUE TITLE
`nest()` preserves attributes (including class) but `unnest()` does not

### ISSUE THREAD

**Issue by petereckley** [tidyverse/tidyr#272] opened 2017-01-17 09:01 UTC
Is this intended behaviour? I could not find it in the docs or NEWS. I would advocate for `unnest()` to preserve attributes since this makes it easier to use in subclasses that specialise data.frames.

**Comment by karimn** [comment] 2017-01-20 17:34
I'm seeing this too. Here's an example:

```r
> nested.data <- tibble(z = 2)
> attr(nested.data, "someattr") <- "xyz"
> test.data <- tibble(x = 1, y = list(nested.data))
> str(test.data)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
 $ x: num 1
 $ y:List of 1
  ..$ :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  1 variable:
  .. ..$ z: num 2
  .. ..- attr(*, "someattr")= chr "xyz"
> test.data %>% unnest(y) %>% str
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
 $ x: num 1
 $ z: num 2
```

**Comment by cb4ds** [comment] 2017-01-26 20:44
I am working on this and ran into the following question regarding whether this is a defect or by design:

A nested column might contain multiple data frames with multiple sets of attributes (potentially with the same or different attribute names).  In my opinion, if the nested column has a single data frame it makes very good sense that it would be useful to preserve the attributes.  However the question of what to do with multiple data frames nested as a list is a problem.  One solution is to drop attributes on multiple dataframes being unnested - however this leads to the undesirable situation where the function behaves differently based on one vs. multiples in content.  This is unintuitive and may lead to more questions than it is worth.  

If it is still desirable to go ahead with the fix and keep attributes on unnest - what is the preferred way to handle multiple data frames being unnested from a list?

Using the example above:
`
> nested.data <- tibble(z = 2)
> attr(nested.data, "someattr") <- "xyz"
> nested.data.2 <- tibble(z = 4)
> attr(nested.data.2, "anotherattr") <- c("ABC", 123)
> test.data <- tibble(x = 1, y = list(nested.data, nested.data.2))
`

**Comment by petereckley** [comment] 2017-01-29 02:41
@cb4ds: this is a good question, which actually goes beyond what I was thinking about. I was focused on the `outer' or highest-level dataframe. This may be in a nested or unnested state, but its attributes could be preserved as its contents are transformed, whether through nesting and unnesting, or through e.g dplyr verbs.

**Comment by karimn** [comment] 2017-01-30 19:08
@cb4ds: I see your point  and I do agree it would not be a good design to have unnest() behave differently depending on how many nested data content rows are being unnested. In that case, I would opt to agree with the dropping of attributes on unnesting. One can always recover the attributes by unnesting a single row using `test.data$y[[row.i.need]]`

**Comment by cb4ds** [comment] 2017-01-30 19:15
Great discussion @petereckley @karimn - I believe the original poster may have meant that the attributes at the top-level are not being maintained - not the nested attributes.  The example may have been misleading - here is the example reworked so that it shows the top-level attributes on the tibble being dropped when unnested.  I think it would make sense to retain _**top-level**_ attributes on unnest.  Thoughts?

```{r}
> nested.data <- tibble(z = 2)
> test.data <- tibble(x = 1, y = list(nested.data))
> attr(test.data, "outerattr") <- c("123", "ABC")
> 
> str(test.data)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
 $ x: num 1
 $ y:List of 1
  ..$ :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  1 variable:
  .. ..$ z: num 2
 - attr(*, "outerattr")= chr  "123" "ABC"
> 
> unnest(test.data, y) %>% str
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1 obs. of  2 variables:
 $ x: num 1
 $ z: num 2
```

**Comment by petereckley** [comment] 2017-01-30 21:32
@cb4ds indeed that is what I meant thanks. The example shows a non class attribute. For the avoidance of doubt, I also envisage class attributes being retained.

**Comment by cb4ds** [comment] 2017-01-30 22:10
@petereckley makes sense - I will make the requisite changes to retain the class and non-class attributes at the top-level when unnesting like when nesting.  Cheers!

**Comment by petereckley** [comment] 2017-01-30 23:48
Marvellous thank you :)

**Comment by hadley** [comment] 2017-06-23 20:36
Possibly related to #206?

Could someone please prepare a minimal reprex using the reprex package?

**Comment by hadley** [comment] 2017-11-15 01:27
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-15 01:27 UTC
Labels: reprex
