### ISSUE TITLE
gather() column selector errors with ncol, dim, etc.

### ISSUE THREAD

**Issue by jules32** [tidyverse/tidyr#352] opened 2017-08-24 17:46 UTC
Hi @hadley and team!

I'm getting an error after upgrading R and RStudio (details below), and I wanted to see if you could look into when you have a chance. 

The error occurs when using base-R's `ncol` or `dim` functions within the `gather()`, which it was able to do in previous versions but now throws this error: `Error in ncol(stocks): could not find function "ncol"`. 

Here is a reprex:

``` r
## I've tried all of these installations today, Aug 24 2017
# install.packages('tidyverse')
# devtools::install_github('tidyverse/tidyverse')
# devtools::install_github('tidyverse/tidyr') 


stocks <- tibble::tibble(
  time = as.Date('2009-01-01') + 0:9,
  X    = rnorm(10, 0, 1),
  Y    = rnorm(10, 0, 2),
  Z    = rnorm(10, 0, 4))

tidyr::gather(stocks, stock, price, 2:ncol(stocks))
#> Error in ncol(stocks): could not find function "ncol"


## just to check that it works with 2:4 hard-coded:
tidyr::gather(stocks, stock, price, 2:4)
#> # A tibble: 30 x 3
#>          time stock       price
#>        <date> <chr>       <dbl>
#>  1 2009-01-01     X -0.37617456
#>  2 2009-01-02     X -0.23506459
#>  3 2009-01-03     X -0.82691073
#>  4 2009-01-04     X  0.98870918
#>  5 2009-01-05     X  1.00480330
#>  6 2009-01-06     X  0.06097522
#>  7 2009-01-07     X  0.48025832
#>  8 2009-01-08     X  1.10165840
#>  9 2009-01-09     X -0.02350605
#> 10 2009-01-10     X -0.55766735
#> # ... with 20 more rows
```

Thank you for the help! 

Version details:

OSX 10.12.4
R version 3.4.1 (2017-06-30)
RStudio Version 1.0.153

**Comment by hadley** [comment] 2017-08-24 18:17
We know about it and will be pushing out a fix very soon.

Is there some reason you're not doing:

```R
tidyr::gather(stocks, stock, price, -1)
```
?

**Comment by jules32** [comment] 2017-08-24 18:21
Thanks @hadley!

Yes, when we were digging in to understand the error we changed our code to `tidyr::gather(stocks, stock, price, -1)` which is much a much tidier way! But still wanted to let you know of the error...and of course you're already on it. 👍 Thanks!

**Comment by lionel-** [comment] 2017-08-24 18:32
Duplicate of #350.

**Closed by lionel-** 2017-08-24 18:32 UTC
