### ISSUE TITLE
0.7.0 breaks programmatic specification of column numbers in gather()

### ISSUE THREAD

**Issue by JCSzamosi** [tidyverse/tidyr#353] opened 2017-08-29 18:49 UTC
Updating from 0.6.1 to 0.7.0 has broken code where column ranges are specified using variable names rather than integers (e.g. start:end instead of 1:4). Not sure if this change was intentional or not, but being able to specify those numbers programmatically (e.g. with ncol()) is really convenient and I would hate to lose it. MRE:

```{r}
library(tidyr)

# Make the data set
dat = data.frame(Genus = 'Escherichia',
					SP1 = rep(10,10),
					SP2 = rep(5,10),
					SP3 = rep(17,10))

# Make the data frame long. This works
dat %>% gather(Species,Count,2:4) -> dat_long

# Specify columns more programmatically. This used to work but now doesn't.
st = 2
dat %>% gather(Species,Count,st:ncol(dat)) -> dat_long

# This also fails, but more excitingly:
st = 1
dat %>% gather(Species,Count,(st+1):ncol(dat)) -> dat_long
```

**Comment by lionel-** [comment] 2017-08-29 20:36
Duplicate of https://github.com/tidyverse/tidyr/issues/350

This will soon be fixed, in the mean time you can install the dev version of tidyselect.

**Closed by lionel-** 2017-08-29 20:36 UTC
