### ISSUE TITLE
Option to sort/arrange names_from in pivot_wider

### ISSUE THREAD

**Issue by wgrundlingh** [tidyverse/tidyr#922] opened 2020-04-01 23:45 UTC
Consider the following example:

```
library(tidyverse)

tibble(
  X = c(1, 1, 2, 2),
  Y = letters[4:1],
  Z = 10 * 1:4
) %>% pivot_wider(
  names_from = Y,
  values_from = Z
)

```

This yields the output

```
# A tibble: 2 x 5
      X     d     c     b     a
  <dbl> <dbl> <dbl> <dbl> <dbl>
1     1    10    20    NA    NA
2     2    NA    NA    30    40
```

An option `names_arrange = TRUE` (say, default is `FALSE`) would yield something similar to

```
library(tidyverse)

tibble(
  X = c(1, 1, 2, 2),
  Y = letters[4:1],
  Z = 10 * 1:4
) %>% arrange(
  Y
) %>% pivot_wider(
  names_from = Y,
  values_from = Z
)

# A tibble: 2 x 5
      X     a     b     c     d
  <dbl> <dbl> <dbl> <dbl> <dbl>
1     2    40    30    NA    NA
2     1    NA    NA    20    10
```

**Comment by hadley** [comment] 2020-04-21 21:11
That would be more typing than your existing code, so it doesn't seem like much of a win?

**Comment by wgrundlingh** [comment] 2020-04-21 21:21
Well, choose a shorter descriptor then. :)

How about an option `arrange = <cols>` where you can specify the column sequence to arrange by, defaulting to the `names_from` if you only specify `arrange`. It just avoids additional pipes and still makes logical sense. That is, I don't think it takes anything away from the functionality or legibility of the code.

Of course, this is just a feature suggestion that I thought could add value...

**Comment by hadley** [comment] 2020-04-21 21:26
Duplicate of #839

**Closed by hadley** 2020-04-21 21:26 UTC
