### ISSUE TITLE
better error message for missing parameter?

### ISSUE THREAD

**Issue by fresques** [tidyverse/tidyr#683] opened 2019-07-17 16:23 UTC
When a `cols` argument is missing from a pivot_longer() call, the error message could be more helpful.

The following does not produce a table, just the following error:
```r
iris %>% pivot_longer()
```
`Error in is_call(expr, paren_sym) : argument "expr" is missing, with no default`

Additionally, just wanted to flag that the behavior is different from using gather() without specifying columns. Not necessarily arguing that pivot_longer() should behave like gather() in this situation, just wanted to note it. The following produces a table with 750 rows, and throws the following warning:
```r
iris %>% gather()
```
`Warning message: attributes are not identical across measure variables; they will be dropped`

**Comment by hadley** [comment] 2019-07-22 22:13
Duplicate of #661 — I knew I had seen this before!

**Closed by hadley** 2019-07-22 22:13 UTC

**Comment by gnguy** [comment] 2019-09-17 18:23
The error mentioned in this issue still appears in tidyr v1.0.0, which should include the changes used to fix #661 via c7d6593. Does that mean that the solution to #661 did not address this issue, and if so, would it be worth reopening this issue or creating a new one?
