### ISSUE TITLE
Empty column name causes errors after using spread()

### ISSUE THREAD

**Issue by tshynik** [tidyverse/tidyr#314] opened 2017-06-20 17:03 UTC
I'm having an issue related to other issues with empty column names ([1576 at dplyr](https://github.com/tidyverse/dplyr/issues/1576) and [364 at readr](https://github.com/tidyverse/readr/issues/364)), but when using spread() and then mutate(). Here's an example:
```r
data_frame(x = sample(letters[1:3], size=20, replace=T), 
           y = sample(c("Y",""), size=20, replace=T)) %>%
  group_by(y,x) %>%
  tally() %>%
  spread(y, n, fill=0) %>%
  mutate( "p" = Y/sum(Y) )
```
Result: `Error in mutate_impl(.data, dots) : Evaluation error: attempt to use zero-length variable name.`

If I use this code instead (only grouping by `y`, so that only the first row's name is blank after the `tally()` step), I get a more appropriate error at the `spread()` step:
```r
data_frame(x = sample(letters[1:3], size=20, replace=T), 
           y = sample(c("Y",""), size=20, replace=T)) %>%
  group_by(y) %>%
  tally() %>%
  spread(y, n, fill=0)
```
Result: `Error: Column 1 must be named`

**Comment by hadley** [comment] 2017-06-23 21:02
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment] 2017-11-15 01:29
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-15 01:29 UTC
Labels: reprex
