### ISSUE TITLE
difference in performance between group_by + nest and nest(-var)

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/tidyr#487] opened 2018-08-14 15:49 UTC
Hello there,

I am working on a reasonably large dataframe (40k obs, 40 variables string and numeric), and I thought these two `dplyr` calls would be equivalent:

```
mydata_full %>% 
  group_by(mygroup) %>% nest()

```
which works

```
# A tibble: 10 x 2
   mygroup     data                 
   <chr>     <list>               
 1 group1  <tibble [2,893 x 38]>
 2 group2  <tibble [2,893 x 38]>
 3 group3  <tibble [2,893 x 38]>
 
```
however, running 

```
mydata_full %>% 
nest(-mygroup)

```
takes a loooong time and the output in the console does not show the `list-column`, but rather the contents of the cells directly (so its hard to read anything!!)

I am happy to work on a reproducible example, but that is not easy. Meanwhile, are there any obvious reasons why this bug would appear?

Thanks!

**Comment by randomgambit** [comment] 2018-08-16 00:26
Here is an example

```
library(dplyr)
library(tibble)
library(tidyr)

N <- 350
M <- 1e6

list1 <- setNames(rep(list(rep(NA, M)), N), paste0("X", seq_len(N)))
list2 <- setNames(rep(list(rep('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', M)), N), paste0("X", seq_len(N)))


df1 <- tibble(!!!list1)
df2 <- tibble(!!!list2)


df <- bind_rows(df2, df1)

> df %>% group_by(X1) %>% nest()
# A tibble: 2 x 2
  X1                               data                      
  <chr>                            <list>                    
1 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa <tibble [1,000,000 x 349]>
2 NA                               <tibble [1,000,000 x 349]>
Warning message:
package ‘bindrcpp’ was built under R version 3.4.4 
> df %>% nest(-X1)
Error: cannot allocate vector of size 7.6 Mb
```

**Comment by hadley** [comment] 2019-01-04 14:50
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by randomgambit** [comment] 2019-01-16 01:45
here it is, buddy!

``` r
library(dplyr)
library(tibble)
library(tidyr)

N <- 350
M <- 1e6

list1 <- setNames(rep(list(rep(NA, M)), N), paste0("X", seq_len(N)))
list2 <- setNames(rep(list(rep('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', M)), N), paste0("X", seq_len(N)))


df1 <- tibble(!!!list1)
df2 <- tibble(!!!list2)


df <- bind_rows(df2, df1)

df %>% group_by(X1) %>% nest()
# A tibble: 2 x 2
X1                               data                      
<chr>                            <list>                    
  1 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa <tibble [1,000,000 x 349]>
  2 NA                               <tibble [1,000,000 x 349]>
  Warning message:
  package ‘bindrcpp’ was built under R version 3.4.4 
df %>% nest(-X1)
Error: cannot allocate vector of size 7.6 Mb
#> Error: <text>:20:34: unexpected symbol
#> 19: # A tibble: 2 x 2
#> 20: X1                               data
#>                                      ^
```

<sup>Created on 2019-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by randomgambit** [comment] 2019-01-16 01:45
summoning @hadley

**Comment by hadley** [comment] 2019-01-19 16:11
I think this smaller reprex illustrates the basic problem:

``` r
library(tidyr)

N <- 5
M <- 1e3
list <- setNames(rep(list(rep(c(NA, "x"), M * 2)), N), paste0("X", seq_len(N)))
df <- as.data.frame(list, stringsAsFactors = FALSE)

df %>% dplyr::group_by(X1) %>% nest() %>% str()
#> Classes 'tbl_df', 'tbl' and 'data.frame':    2 obs. of  2 variables:
#>  $ X1  : chr  NA "x"
#>  $ data:List of 2
#>   ..$ :Classes 'tbl_df', 'tbl' and 'data.frame': 2000 obs. of  4 variables:
#>   .. ..$ X2: chr  NA NA NA NA ...
#>   .. ..$ X3: chr  NA NA NA NA ...
#>   .. ..$ X4: chr  NA NA NA NA ...
#>   .. ..$ X5: chr  NA NA NA NA ...
#>   ..$ :Classes 'tbl_df', 'tbl' and 'data.frame': 2000 obs. of  4 variables:
#>   .. ..$ X2: chr  "x" "x" "x" "x" ...
#>   .. ..$ X3: chr  "x" "x" "x" "x" ...
#>   .. ..$ X4: chr  "x" "x" "x" "x" ...
#>   .. ..$ X5: chr  "x" "x" "x" "x" ...
df %>% nest(-X1) %>% str()
#> 'data.frame':    2 obs. of  2 variables:
#>  $ X1  : chr  NA "x"
#>  $ data:List of 2
#>   ..$ :'data.frame': 2000 obs. of  4 variables:
#>   .. ..$ X2: chr  NA NA NA NA ...
#>   .. ..$ X3: chr  NA NA NA NA ...
#>   .. ..$ X4: chr  NA NA NA NA ...
#>   .. ..$ X5: chr  NA NA NA NA ...
#>   ..$ :'data.frame': 2000 obs. of  4 variables:
#>   .. ..$ X2: chr  "x" "x" "x" "x" ...
#>   .. ..$ X3: chr  "x" "x" "x" "x" ...
#>   .. ..$ X4: chr  "x" "x" "x" "x" ...
#>   .. ..$ X5: chr  "x" "x" "x" "x" ...
```

<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

So I'm pretty sure this is a duplicate of #475

**Closed by hadley** 2019-01-19 16:11 UTC
Labels: reprex
