### ISSUE TITLE
`pivot_wider` not working with class <Period>

### ISSUE THREAD

**Issue by bertrandh** [tidyverse/tidyr#916] opened 2020-03-20 04:49 UTC
*Brief description of the problem:*
`pivot_wider` throws a strange error when used with a value_from column of type `<Period>` (as output from lubridate).
I am using R-3.6.3, lubridate_1.7.4, dbplyr_1.4.2.

*Reprex:*
```r
df_0 <- tibble(period_name   = c("a", "b", "c"), 
               period_value  = c("1:1:1", 
                                 "2:2:2", 
                                 "4:4:4")) %>% 
         mutate(period_value = lubridate::hms(period_value))

df_0
## A tibble: 3 x 2
#  period_name period_value
#  <chr>       <Period>
#1 a           1H 1M 1S
#2 b           2H 2M 2S
#3 c           4H 4M 4S
```
Now, let's try widening the data frame
```r
df_0 %>% pivot_wider(names_from = period_name, values_from = period_value)
#Error: No common type for `value` <Period> and `x` <Period>.
```
This error does not make sense to me.
BTW, at least it throws an error, whereas `spread` silently messed it up (see [Stackoverflow question](https://stackoverflow.com/questions/60751518/lubridate-periods-get-messed-up-after-using-dplyr-spread)).

It works fine, though, with date_time type:
```r
df_1 <- tibble(dttm_name   = c("a", "b", "c"), 
               dttm_value  = c("2020-01-01 1:1:1", 
                               "2020-02-03 2:2:2", 
                               "2020-05-10 4:4:4")) %>% 
         mutate(dttm_value = lubridate::as_datetime(dttm_value))

df_1
## A tibble: 3 x 2
#  dttm_name dttm_value
#  <chr>     <dttm>
#1 a         2020-01-01 01:01:01
#2 b         2020-02-03 02:02:02
#3 c         2020-05-10 04:04:04

df_1 %>% pivot_wider(names_from = dttm_name, values_from = dttm_value)
## A tibble: 1 x 3
#  a                   b                   c
#  <dttm>              <dttm>              <dttm>
#1 2020-01-01 01:01:01 2020-02-03 02:02:02 2020-05-10 04:04:04
```
Is that something wrong with `pivot_wider` (and `spread`) or with lubridate's `Period` class?

**Comment by hadley** [comment] 2020-03-20 13:05
Duplicate of https://github.com/r-lib/vctrs/issues/919

**Closed by hadley** 2020-03-20 13:05 UTC
