### ISSUE TITLE
Incorrect order of column names using pivot_wider() with names_glue and names_sort

### ISSUE THREAD

**Issue by wphampton** [tidyverse/tidyr#1064] opened 2020-11-20 16:30 UTC
Using `pivot_wider()` along with params `names_glue` and `names_sort`, the columns are not sorted as expected.

The code below will return a columns names in this order: 
`Name, Height_Value, Temp_Value, Weight_Value, Height_Date, Temp_Date, Weight_Date`

However I would expect:
`Name, Height_Date, Height_Value, Temp_Date, Temp_Value, Weight_Date, Weight_Value`

Likely related to [Issue 839](https://github.com/tidyverse/tidyr/issues/839), though might be a separate situation altogether.

```r
library(tidyr)

df <- data.frame(
  "Name" = c("Sally","Sally","Sally","Bob","Bob","Bob","Jack","Jack","Jack"),
  "Measure" = c("Height","Weight","Temp","Height","Weight","Temp","Height","Weight","Temp"),
  "Value" = c(67,145,98.4,71,175,98.8,73,180,98.6),
  "Date" = c("Jan 1","Jan 12","Jan 20","Mar 3","Mar 11","Mar 16","Jun 4","Jun 8","Jun 24")
)

pivot_wider(df, names_from = c(Measure), values_from = c(Value, Date), 
                names_glue = "{Measure}_{.value}", names_sort = TRUE)
```

Thanks for this great package! -Wes

**Comment by hadley** [comment] 2021-02-17 22:45
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by wphampton** [comment] 2021-02-19 13:52
Yes, output below having tidyr_1.1.2

``` r
library(tidyr)

df <- data.frame(
  "Name" = c("Sally","Sally","Sally","Bob","Bob","Bob","Jack","Jack","Jack"),
  "Measure" = c("Height","Weight","Temp","Height","Weight","Temp","Height","Weight","Temp"),
  "Value" = c(67,145,98.4,71,175,98.8,73,180,98.6),
  "Date" = c("Jan 1","Jan 12","Jan 20","Mar 3","Mar 11","Mar 16","Jun 4","Jun 8","Jun 24")
)

pivot_wider(df, names_from = c(Measure), values_from = c(Value, Date), 
                names_glue = "{Measure}_{.value}", names_sort = TRUE)
#> # A tibble: 3 x 7
#>   Name  Height_Value Temp_Value Weight_Value Height_Date Temp_Date Weight_Date
#>   <chr>        <dbl>      <dbl>        <dbl> <chr>       <chr>     <chr>      
#> 1 Sally           67       98.4          145 Jan 1       Jan 20    Jan 12     
#> 2 Bob             71       98.8          175 Mar 3       Mar 16    Mar 11     
#> 3 Jack            73       98.6          180 Jun 4       Jun 24    Jun 8
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by DavisVaughan** [comment] 2021-12-14 20:08
`names_sort` is purely about sorting the `names_from` columns before they are combined with the `values_from` names.

What you want is to create a spec ahead of time and then `arrange()` it

``` r
library(tidyverse)

df <- data.frame(
  "Name" = c("Sally","Sally","Sally","Bob","Bob","Bob","Jack","Jack","Jack"),
  "Measure" = c("Height","Weight","Temp","Height","Weight","Temp","Height","Weight","Temp"),
  "Value" = c(67,145,98.4,71,175,98.8,73,180,98.6),
  "Date" = c("Jan 1","Jan 12","Jan 20","Mar 3","Mar 11","Mar 16","Jun 4","Jun 8","Jun 24")
)

spec <- build_wider_spec(
  df, 
  names_from = Measure, 
  values_from = c(Value, Date), 
  names_glue = "{Measure}_{.value}"
)
spec
#> # A tibble: 6 × 3
#>   .name        .value Measure
#>   <chr>        <chr>  <chr>  
#> 1 Height_Value Value  Height 
#> 2 Weight_Value Value  Weight 
#> 3 Temp_Value   Value  Temp   
#> 4 Height_Date  Date   Height 
#> 5 Weight_Date  Date   Weight 
#> 6 Temp_Date    Date   Temp

spec <- arrange(spec, Measure, .value)
spec
#> # A tibble: 6 × 3
#>   .name        .value Measure
#>   <chr>        <chr>  <chr>  
#> 1 Height_Date  Date   Height 
#> 2 Height_Value Value  Height 
#> 3 Temp_Date    Date   Temp   
#> 4 Temp_Value   Value  Temp   
#> 5 Weight_Date  Date   Weight 
#> 6 Weight_Value Value  Weight

pivot_wider_spec(df, spec)
#> # A tibble: 3 × 7
#>   Name  Height_Date Height_Value Temp_Date Temp_Value Weight_Date Weight_Value
#>   <chr> <chr>              <dbl> <chr>          <dbl> <chr>              <dbl>
#> 1 Sally Jan 1                 67 Jan 20          98.4 Jan 12               145
#> 2 Bob   Mar 3                 71 Mar 16          98.8 Mar 11               175
#> 3 Jack  Jun 4                 73 Jun 24          98.6 Jun 8                180
```

I'm calling this a duplicate of #839 since it can be solved with the same general solution that was mentioned in https://github.com/tidyverse/tidyr/issues/839#issuecomment-993932843

**Closed** 2021-12-14 20:08 UTC
Labels: feature, pivoting :recycle:
