### ISSUE TITLE
Unnesting vectors of datettimes (POSIXct)

### ISSUE THREAD

**Issue by sebkopf** [tidyverse/tidyr#432] opened 2018-03-02 16:01 UTC
It seems not possible to `unnest` POSIXct (datetime) vectors. Should this be possible in tidyr? (apologies if it is the intentional expected behaviour).

See example below:

```
(df <- data_frame(number = list(42), dttm = list(lubridate::now())) )
# # A tibble: 1 x 2
#   number    dttm      
#   <list>    <list>    
# 1 <dbl [1]> <dttm [1]>

unnest(df, number)
# # A tibble: 1 x 2
#   dttm       number
#   <list>      <dbl>
# 1 <dttm [1]>   42.0

unnest(df, dttm)
# Error: Each column must either be a list of vectors or a list of data frames [dttm]
```

Thanks

**Comment by hadley** [comment] 2018-03-02 16:13
Duplicate of #407

**Closed by hadley** 2018-03-02 16:13 UTC
