### ISSUE TITLE
Fill does not behave as expected when using with group_by

### ISSUE THREAD

**Issue by naveennjs** [tidyverse/tidyr#318] opened 2017-06-23 20:39 UTC
Was this fixed ? I am doing something similar.
df%>%group_by(id,name%>%fill(amount) does not yield the correct results. I am using tidyR version 0.6.1

**Comment by naveennjs** [comment] 2017-06-23 20:40
Was this fixed ? I am doing something similar to:
df%>%group_by(id,name%>%fill(amount) does not yield the correct results. I am using tidyR version 0.6.1

I am not obtaining the expected results

**Comment by hadley** [comment] 2017-06-23 21:02
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2017-11-15 01:29
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-11-15 01:29 UTC
Labels: reprex
