### ISSUE TITLE
Issue with 1.0.0 'unnest()' function 

### ISSUE THREAD

**Issue by kaybenleroll** [tidyverse/tidyr#733] opened 2019-09-12 22:00 UTC
There appears to be an issue using `unnest()` with the new logic.

I have attached sample data.

---

```r
data_tbl <- structure(list(symbol = c("AAPL", "AAPL"), field = c("BOOK_VAL_PER_SH", 
"IS_EPS"), data = list(structure(list(date = structure(c(11048L, 
11139L, 11230L, 11321L, 11412L, 11503L, 11594L, 11685L, 11776L, 
11867L, 11958L, 12049L, 12140L, 12231L, 12322L, 12413L, 12504L, 
12595L, 12686L, 12777L, 12868L, 13050L, 13148L, 13239L, 13330L, 
13421L, 13512L, 13603L, 13694L, 13785L, 13876L, 13967L, 14058L, 
14149L, 14240L, 14331L, 14422L, 14513L, 14604L, 14695L, 14786L, 
14877L, 14968L, 15059L, 15150L, 15241L, 15339L, 15430L, 15521L, 
15612L, 15703L, 15794L, 15885L, 15976L, 16067L, 16158L, 16249L, 
16340L, 16431L, 16522L, 16613L, 16704L, 16795L, 16886L, 16977L, 
17068L, 17166L, 17257L, 17348L, 17439L, 17530L, 17621L, 17712L, 
17803L), class = "Date"), value = c(0.8924, 0.8853, 0.8578, 0.7672, 
0.7705, 0.7863, 0.7979, 0.8037, 0.8097, 0.8093, 0.8149, 0.8161, 
0.8088, 0.8171, 0.8225, 0.8387, 0.8602, 0.8923, 0.9262, 1.0223, 
1.1083, 1.2708, 1.4157, 1.4606, 1.5626, 1.6677, 1.8658, 2.0275, 
2.2085, 2.3797, 2.7322, 2.9444, 3.1926, 3.5857, 3.6755, 3.8939, 
4.1288, 5.0233, 5.6381, 6.1796, 6.742, 7.4536, 8.479, 9.4979, 
10.6873, 11.778, 13.8003, 15.6608, 17.0322, 17.9802, 19.3747, 
20.5891, 19.398, 19.6281, 20.759, 19.9229, 20.1931, 19.0153, 
21.167, 22.388, 22.0277, 21.3946, 23.1342, 23.8128, 23.4632, 
24.0339, 25.1911, 25.7562, 25.6152, 26.1494, 27.5893, 25.6668, 
23.7355, 22.5336)), row.names = c(NA, -74L), class = c("tbl_df", 
"tbl", "data.frame")), structure(list(date = structure(c(11048L, 
11139L, 11230L, 11321L, 11412L, 11503L, 11594L, 11685L, 11776L, 
11867L, 11958L, 12049L, 12140L, 12231L, 12322L, 12413L, 12504L, 
12595L, 12686L, 12777L, 12868L, 12959L, 13050L, 13148L, 13239L, 
13330L, 13421L, 13512L, 13603L, 13694L, 13785L, 13876L, 13967L, 
14058L, 14149L, 14240L, 14331L, 14422L, 14513L, 14604L, 14695L, 
14786L, 14877L, 14968L, 15059L, 15150L, 15241L, 15339L, 15430L, 
15521L, 15612L, 15703L, 15794L, 15885L, 15976L, 16067L, 16158L, 
16249L, 16340L, 16431L, 16522L, 16613L, 16704L, 16795L, 16886L, 
16977L, 17068L, 17166L, 17257L, 17348L, 17439L, 17530L, 17621L, 
17712L, 17803L), class = "Date"), value = c(0.0514, 0.0443, 0.0371, 
-0.0414, 0.0086, 0.0121, 0.0136, 0.0079, 0.0079, 0.0064, -0.0093, 
-0.0014, 0.0029, 0.0036, 0.0086, 0.0121, 0.0093, 0.0114, 0.02, 
0.0536, 0.0514, 0.0557, 0.0743, 0.0971, 0.07, 0.0786, 0.09, 0.1686, 
0.1286, 0.1386, 0.1429, 0.2586, 0.1786, 0.1829, 0.3614, 0.3629, 
0.26, 0.2929, 0.4029, 0.5343, 0.4843, 0.51, 0.6729, 0.9329, 0.9271, 
1.1271, 1.0186, 2.0043, 1.7786, 1.3457, 1.2514, 1.99, 1.4514, 
1.0729, 1.1871, 2.0843, 1.67, 1.29, 1.43, 3.08, 2.34, 1.86, 1.97, 
3.3, 1.91, 1.43, 1.68, 3.38, 2.11, 1.68, 2.08, 3.92, 2.75, 2.36, 
2.94)), row.names = c(NA, -75L), class = c("tbl_df", "tbl", "data.frame"
)))), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
-2L))

data_tbl %>% glimpse()

data_tbl %>% unnest(data)
```

The output for this was:

> Error in vec_rbind(!!!x, .ptype = ptype) : 
>   REAL() can only be applied to a 'numeric', not a 'integer'
> 

Let me know if you need anything further to make this issue more useful.

**Comment by kaybenleroll** [comment] 2019-09-13 07:20
The above data was originally from Bloomberg I think, so it would have come straight from that - I imagine they are providing dates as integers, much like what happens with Excel.

It sounds like the easiest thing to do is to convert the date to a numeric base instead of integer and it should work then?

**Comment by yutannihilation** [comment] 2019-09-13 09:14
As shown in the example of r-lib/vctrs#396, even base functions like `seq.Date()` can return integer Date. So, I think we should not expect the date is always numeric.

``` r
is.integer(seq(Sys.Date(), length.out = 3, by = 1))
#> [1] TRUE
```

<sup>Created on 2019-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2019-09-13 12:22
Closing as it's a duplicate of the vctrs issue.

**Closed by hadley** 2019-09-13 12:22 UTC

**Comment by krlmlr** [comment] 2019-09-13 13:47
@kaybenleroll: Yes, currently you need to convert manually to "numeric dates".
