### ISSUE TITLE
expand_grid not working in combination with do.call / lift_dl when passing data.frames in a list

### ISSUE THREAD

**Issue by fabiangehring** [tidyverse/tidyr#989] opened 2020-07-02 06:05 UTC
When using tidyr::expand_grid in combination with do.call (or lift_dl) the output is not the same compared to a direct call of the function with multiple (tibble) elements.

Expected:
```
dat <- list(tibble(a = 1:2), NULL, tibble(b = 2))
tidyr::expand_grid(dat[[1]], dat[[2]], dat[[3]], .name_repair = "minimal")
```

Different result when using do.call or lift_dl:
```
do.call(tidyr::expand_grid, c(dat, list(.name_repair = "minimal"))) # version do.call
purrr::lift_dl(expand_grid)(dat, .name_repair = "minimal") # version lift_dl
```

Using latest tidyr on cran (1.1.0) 
Am I missing anything?

**Comment by hadley** [comment] 2020-07-10 20:29
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment] 2020-08-28 16:46
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-08-28 16:46 UTC
