### ISSUE TITLE
separate_rows() drops columns of 0 row data.frames

### ISSUE THREAD

**Issue by d-cameron** [tidyverse/tidyr#470] opened 2018-06-20 05:46 UTC
Using tidyr_0.8.0
```
data.frame(a=character(), b=character()) %>% separate_rows(b)
```
Expected behaviour: data.frame with 0 rows and 2 columns
Actual behaviour: data.frame with 0 rows and 1 column (b is dropped)

This behaviour is problematic as it requires separate code paths in the surrounding logic based on whether or not the data.frame is empty.

**Comment by hadley** [comment] 2019-01-04 15:51
Reprex:

``` r
library(tidyr)
data.frame(a = character(), b = character()) %>% 
  separate_rows(b) %>% 
  names()
#> [1] "a"

data.frame(a = "x", b = "") %>% 
  separate_rows(b) %>% 
  names()
#> [1] "a" "b"

data.frame(a = "x", b = "x,y") %>% 
  separate_rows(b) %>% 
  names()
#> [1] "a" "b"
```

Looks like the root cause is `unnest()`:

``` r
library(tidyr)
data.frame(a = character(), b = character()) %>% unnest(b)
#> [1] a
#> <0 rows> (or 0-length row.names)
```

**Comment by hadley** [comment] 2019-01-04 15:53
Which makes it a duplicate of #483

**Closed by hadley** 2019-01-04 15:53 UTC
Labels: bug, tidy-dev-day :nerd_face:, trees :evergreen_tree:
