### ISSUE TITLE
Silent fail with unite

### ISSUE THREAD

**Issue by sdelear** [tidyverse/tidyr#467] opened 2018-06-18 03:49 UTC
Trying to combine several columns into one, then replace some of the data.  Have tried this before and after converting character strings to factors.  The new column is not created and no data is passed into it.  I have tried simply copying "City" to "Community" to create a community column.  R version 3.4.2 with RStudio.  

unite(copyr, "Community", c("City", "Town.District","Hamlet.Community.Area"), sep="")

and

copyr %>% unite(copyr, "Community", c("City", "Town.District","Hamlet.Community.Area"), sep="")

Length  Class   Mode 
     0   NULL   NULL 
Warning message:
Unknown or uninitialised column: 'Community'. 
> copyr %>% unite(copyr, "Community", c("City", "Town.District","Hamlet.Community.Area"), sep="")
Error: Unknown column `Community` 

This is doing nothing and failing silently.

**Comment by hadley** [comment] 2018-06-27 19:36
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2019-01-04 15:46
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2019-01-04 15:46 UTC
Labels: reprex
