### ISSUE TITLE
Error when running "Duplicated column names section" of tidyr Pivoting vignette.

### ISSUE THREAD

**Issue by 7670367** [tidyverse/tidyr#878] opened 2020-02-10 15:43 UTC
When running the second example in the "[Duplicated column names](https://tidyr.tidyverse.org/dev/articles/pivot.html#duplicated-column-names)" section of the tidyr Pivoting vignette (code below) I get an error:
```
> df <- tibble(id = 1:3, x1 = 4:6, x2 = 5:7, y1 = 7:9, y2 = 10:12)
> df %>% pivot_longer(-id, names_to = ".value", names_pattern = "(.).")
New names:
* .value -> .value...2
* .value -> .value...3
Error: `spec` must have `.name` and `.value` columns
```
Is this a problem with the test dataframe, the arguments to `pivot_longer`, or something I'm doing wrong? Thanks.

**Comment by batpigandme** [comment] 2020-02-10 15:48
I'm not able to reproduce this. Could you please make a full [reprex](https://reprex.tidyverse.org/) of this and set your session_info to true (this will append your session info). 

``` r
library(tidyverse)
df <- tibble(id = 1:3, y = 4:6, y = 5:7, y = 7:9, .name_repair = "minimal")
df %>% pivot_longer(-id, names_to = "name", values_to = "value")
#> # A tibble: 9 x 3
#>      id name  value
#>   <int> <chr> <int>
#> 1     1 y         4
#> 2     1 y         5
#> 3     1 y         7
#> 4     2 y         5
#> 5     2 y         6
#> 6     2 y         8
#> 7     3 y         6
#> 8     3 y         7
#> 9     3 y         9
```

<sup>Created on 2020-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by 7670367** [comment] 2020-02-10 15:57
Here is the `reprex` version:
``` r
library(tidyverse)
df <- tibble(id = 1:3, x1 = 4:6, x2 = 5:7, y1 = 7:9, y2 = 10:12)
df %>% pivot_longer(-id, names_to = ".value", names_pattern = "(.).")
#> New names:
#> * .value -> .value...2
#> * .value -> .value...3
#> Error: `spec` must have `.name` and `.value` columns
```

<sup>Created on 2020-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.2 (2019-12-12)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/Chicago             
#>  date     2020-02-10                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                     
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.1)             
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.1)             
#>  broom         0.5.4      2020-01-27 [1] CRAN (R 3.6.2)             
#>  callr         3.4.1      2020-01-24 [1] CRAN (R 3.6.2)             
#>  cellranger    1.1.0      2016-07-27 [1] CRAN (R 3.6.2)             
#>  cli           2.0.1      2020-01-08 [1] CRAN (R 3.6.2)             
#>  colorspace    1.4-1      2019-03-18 [1] CRAN (R 3.6.1)             
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.1)             
#>  DBI           1.1.0      2019-12-15 [1] CRAN (R 3.6.2)             
#>  dbplyr        1.4.2      2019-06-17 [1] CRAN (R 3.6.2)             
#>  desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.1)             
#>  devtools      2.2.1      2019-09-24 [1] CRAN (R 3.6.1)             
#>  digest        0.6.23     2019-11-23 [1] CRAN (R 3.6.1)             
#>  dplyr       * 0.8.4      2020-01-31 [1] CRAN (R 3.6.2)             
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.1)             
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.1)             
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.2)             
#>  forcats     * 0.4.0      2019-02-17 [1] CRAN (R 3.6.2)             
#>  fs            1.3.1      2019-05-06 [1] CRAN (R 3.6.1)             
#>  generics      0.0.2      2018-11-29 [1] CRAN (R 3.6.2)             
#>  ggplot2     * 3.2.1      2019-08-10 [1] CRAN (R 3.6.1)             
#>  glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.1)             
#>  gtable        0.3.0      2019-03-25 [1] CRAN (R 3.6.1)             
#>  haven         2.2.0      2019-11-08 [1] CRAN (R 3.6.2)             
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.2)             
#>  hms           0.5.3      2020-01-08 [1] CRAN (R 3.6.2)             
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.1)             
#>  httr          1.4.1      2019-08-05 [1] CRAN (R 3.6.1)             
#>  jsonlite      1.6        2018-12-07 [1] CRAN (R 3.6.1)             
#>  knitr         1.27       2020-01-16 [1] CRAN (R 3.6.2)             
#>  lattice       0.20-38    2018-11-04 [2] CRAN (R 3.6.2)             
#>  lazyeval      0.2.2      2019-03-15 [1] CRAN (R 3.6.1)             
#>  lifecycle     0.1.0      2019-08-01 [1] CRAN (R 3.6.1)             
#>  lubridate     1.7.4      2018-04-11 [1] CRAN (R 3.6.2)             
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.1)             
#>  memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.1)             
#>  modelr        0.1.5      2019-08-08 [1] CRAN (R 3.6.2)             
#>  munsell       0.5.0      2018-06-12 [1] CRAN (R 3.6.1)             
#>  nlme          3.1-143    2019-12-10 [1] CRAN (R 3.6.1)             
#>  pillar        1.4.3      2019-12-20 [1] CRAN (R 3.6.2)             
#>  pkgbuild      1.0.6      2019-10-09 [1] CRAN (R 3.6.1)             
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.1)             
#>  pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.6.1)             
#>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.2)             
#>  processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.1)             
#>  ps            1.3.0      2018-12-21 [1] CRAN (R 3.6.1)             
#>  purrr       * 0.3.3      2019-10-18 [1] CRAN (R 3.6.1)             
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.1)             
#>  Rcpp          1.0.3      2019-11-08 [1] CRAN (R 3.6.1)             
#>  readr       * 1.3.1      2018-12-21 [1] CRAN (R 3.6.2)             
#>  readxl        1.3.1      2019-03-13 [1] CRAN (R 3.6.2)             
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.2)             
#>  reprex        0.3.0      2019-05-16 [1] CRAN (R 3.6.2)             
#>  rlang         0.4.4      2020-01-28 [1] CRAN (R 3.6.2)             
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.2)             
#>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.1)             
#>  rvest         0.3.5      2019-11-08 [1] CRAN (R 3.6.2)             
#>  scales        1.1.0      2019-11-18 [1] CRAN (R 3.6.1)             
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.1)             
#>  stringi       1.4.5      2020-01-11 [1] CRAN (R 3.6.1)             
#>  stringr     * 1.4.0      2019-02-10 [1] CRAN (R 3.6.1)             
#>  testthat      2.3.1      2019-12-01 [1] CRAN (R 3.6.1)             
#>  tibble      * 2.1.3      2019-06-06 [1] CRAN (R 3.6.1)             
#>  tidyr       * 1.0.2      2020-01-24 [1] CRAN (R 3.6.2)             
#>  tidyselect    1.0.0      2020-01-27 [1] CRAN (R 3.6.2)             
#>  tidyverse   * 1.3.0      2019-11-21 [1] CRAN (R 3.6.2)             
#>  usethis       1.5.1      2019-07-04 [1] CRAN (R 3.6.1)             
#>  vctrs         0.2.2      2020-01-24 [1] CRAN (R 3.6.2)             
#>  withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.1)             
#>  xfun          0.12       2020-01-13 [1] CRAN (R 3.6.2)             
#>  xml2          1.2.2.9000 2020-01-20 [1] Github (r-lib/xml2@a7a50de)
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.2)             
#> 
#> [1] C:/Users/JT/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.2/library
```

</details>

**Comment by batpigandme** [comment] 2020-02-10 16:32
Hmm. Well, the good news is that it seems to be fixed in the development version. Possibly here: https://github.com/tidyverse/tidyr/commit/e1b548ba8d4d31e2a674604b92c944dd263b5ac5

But I'm not 100% sure.

**Comment by 7670367** [comment] 2020-02-10 19:34
I installed the development version (`devtools::install_github("tidyverse/tidyr")`) and the error went away. Thanks!

**Closed** 2020-02-10 19:35 UTC
