### ISSUE TITLE
Why is the replace argument of replace_na() so strict?

### ISSUE THREAD

**Issue by Ljupch0** [tidyverse/tidyr#843] opened 2019-12-25 08:55 UTC
`replace`	    If `data` is a data frame, a named list giving the value to replace NA with for each column. If data is a vector, a single value used for replacement.

I believe that if the users puts a single value to replace NAs and inputs a data frame, the same replacement value should be applied across all columns. If however the user wants a more elaborate replacement pattern, a named list can be provided. I think the case where you replace NAs across the board is quite common.

**Comment by huftis** [comment] 2020-03-31 12:02
If #912 was implemented, this could be written as:

```r
df %>% 
  replace_na(across(everything(), 0))
```

**Comment by hadley** [comment] 2020-04-01 17:03
Closing as duplicate of #912 since this will be fixed by better documentation.

**Closed by hadley** 2020-04-01 17:03 UTC
