### ISSUE TITLE
Understanding memory usage with nest/spread/gather: removing object still leaves used memory?

### ISSUE THREAD

**Issue by MatthieuStigler** [tidyverse/tidyr#1059] opened 2020-11-03 23:39 UTC
I am trying to understand why creating and deleting some objects created with `tidyr` is still keeping memory busy. I expected that memory usage would come back to the initial level, but it does not seem to be the case. This seems to happen in particular when spreading/gather a nested object?

In the example below, my session starts with 34 MB, creating objects raises memory usage to 848MB, but after removing everything created, I am still using 448 MB (and I would have expected back to 34MB)? Are some objects still stored in a cache in a local environment? How can I find/remove them?

Thanks! 

``` r
library(magrittr)

mem_first <- pryr::mem_used()
#> Registered S3 method overwritten by 'pryr':
#>   method      from
#>   print.bytes Rcpp
mem_first
#> 34.7 MB

df1 <- tibble::as_tibble(as.data.frame(matrix(rep(1,1e08), ncol=5))) %>% 
  dplyr::mutate(group=rep(c("a", "b"), each=1e08/(2*5))) %>% 
  tidyr::nest(data=-group)


df2 <- df1 %>% 
  tidyr::spread(group, data) %>% 
  tidyr::gather(group, data, a, b)

pryr::mem_used()
#> 848 MB

## remove first
rm(df1, df2)
ls(all.names = TRUE)
#> [1] "mem_first"
pryr::mem_used()
#> 448 MB
mem_first
#> 34.7 MB
```

<sup>Created on 2020-11-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2021-02-17 22:51
Slightly more minimal code with a kinder number of columns:

``` r
library(tidyr)

mem_first <- lobstr::mem_used()
mem_first
#> 45,228,856 B

df1 <- as_tibble(as.data.frame(matrix(rep(1, 1e7), ncol = 5))) %>%
  dplyr::mutate(group = rep(c("a", "b"), each = 1e7 / (2 * 5))) %>%
  nest(data = -group)

df2 <- df1 %>%
  spread(group, data) %>%
  gather(group, data, a, b)

lobstr::mem_used()
#> 132,995,016 B

rm(df1, df2)
ls(all.names = TRUE)
#> [1] "mem_first"

lobstr::mem_used()
#> 93,007,352 B
```

<sup>Created on 2021-02-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I can't see how tidyr could be to blame for this, but @lionel- this would be a good test for reftracer.

**Comment by lionel-** [comment] 2021-03-01 17:36
I can reproduce on R 4.0 but not in R-devel. So this can probably be closed.

**Comment by lionel-** [comment] 2021-03-01 21:51
I used a manually compiled R 4.0 (to expose the precious list and see if memtools could find the source of the leak) and couldn't reproduce either. So that was weird. I checked that all package versions matched.

So maybe the installed version of tidyr was compiled with an older cpp11, which means they would be effectively different versions even though they are nominally the same. I reinstalled from source and then the issue was gone. Bisecting through cpp11's history shows that the leak was fixed in r-lib/cpp11#92. This seems to be the relevant part:

> Moved the doubly-linked list of preserved objects from a static object in c++ named cpp11::protect_list to an internal in R named cpp11:::.preserve_list. This allows the list to be a singleton since any shared object we load will look up the same cpp11:::.preserve_list. By contrast a new c++ static variable will be instantiated for each translation unit we compile, resulting in multiple unrelated preserve_lists: 

I'll try and see if memtools could have been used to detect this leak tomorrow. I am surprised that the CRAN version of tidyr is still compiled against such an old version of cpp11 (released early October). cc @jimhester

**Comment by jimhester** [comment] 2021-03-02 00:37
My guess is both the OP and Hadley were using tidyr compiled against an older version of cpp11. CRAN does re-compile reverse dependencies for LinkingTo packages when the package is updated, so the current CRAN version should be OK.

**Comment by lionel-** [comment] 2021-03-02 07:14
The current CRAN version of tidyr still seems to be compiled against a several versions old cpp11, which is what surprised me.

**Comment by hadley** [comment] 2021-03-02 12:52
I think it's probably worth doing a patch release just to force an update, so I'll kick that off.

**Closed by hadley** 2021-03-02 12:52 UTC

**Comment by jimhester** [comment] 2021-03-02 15:09
Ah at least windows does update them, maybe the macOS builder does not?
