### ISSUE TITLE
Different behavior for nest

### ISSUE THREAD

**Issue by abichat** [tidyverse/tidyr#482] opened 2018-07-30 13:00 UTC
Here, the first three codes produce the same desired output (`iris` nested by `Species`) whereas the fourth one doesn't.

```
library(tidyverse)

iris %>% 
  as_tibble() %>% 
  group_by(Species) %>% 
  nest()

iris %>% 
  group_by(Species) %>% 
  nest()

iris %>% 
  as_tibble() %>% 
  nest(-Species)

iris %>% 
  nest(-Species)
```

```
> identical(nest(as_tibble(iris), -Species), nest(group_by(iris, Species)))
[1] TRUE
> identical(nest(as_tibble(iris), -Species), nest(iris, -Species))
[1] FALSE
```

**Comment by markdly** [comment] 2018-07-31 10:33
Just adding a link here to #475 which I think is related / very similar to this issue

**Comment by hadley** [comment] 2019-01-04 14:54
It returns a data frame instead of a tibble, so it appears to be duplicate of #475

**Closed by hadley** 2019-01-04 14:54 UTC
